### ISSUE TITLE
Update build instructions [depends on changes in T4]

### ISSUE THREAD

**Issue by mvreeuwijk** [uDALES/u-dales#209]

**Comment by dc2917** [comment]
I thought I'd note down some things here, having gone through the build instructions recently:

- If the [Singularity section](https://udales.github.io/u-dales/udales-getting-started/#singularity) is staying, I think the top-level [Getting Started](https://udales.github.io/u-dales/udales-getting-started/#getting-started) paragraph should briefly state the options - i.e. with or without singularity - so that users know there is an alternative before jumping straight into installing singularity - particularly if this is not the approach taken by current members of the group.
- Again, if the Singularity section is staying, the clone command should be fixed:
`https://github.com/uDALES/u-dales.git`
-> 
`git clone --recurse-submodules https://github.com/uDALES/u-dales`
- The slides suggest removing the cookiecutter approach. I don't have strong feelings but I didn't take this approach, and if no one else in the group does then it's just another complication, so I'd be in favour of removing it.
- Running `copy_inputs.sh` as described [here](https://udales.github.io/u-dales/udales-getting-started/#set-up) will need updating as of #201 
-
